spring.application.name=ProyectoComida
server.port=${PORT:8080}
api.version=${API_VERSION:v1}

# PostgreSQL en Render
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# No recrear la BD cada vez
spring.jpa.hibernate.ddl-auto=validate

# Desactivar logs SQL en producción
spring.jpa.show-sql=false
logging.level.org.hibernate.orm.jdbc.bind=WARN

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

