INSERT INTO PLATOS (id, nombre, descripcion, tipo, categoria, precio, variante, cantidad, is_deleted) VALUES
(1, 'Ensalada César', 'Lechuga romana, crutones, queso parmesano y salsa césar casera', 'ALMUERZO', 'ENTRANTE', 12.50, 'ESTANDAR', 50, false),
(2, 'Solomillo a la Pimienta', 'Corte de res tierno bañado en salsa de pimienta negra con guarnición de patatas', 'CENA', 'PRINCIPAL', 24.00, 'ESTANDAR', 20, false),
(3, 'Salmón a la Plancha', 'Filete de salmón fresco con espárragos trigueros y limón', 'ALMUERZO', 'PRINCIPAL', 18.50, 'SIN_GLUTEN', 30, false),
(4, 'Risotto de Setas', 'Arroz cremoso con variedad de hongos silvestres y aceite de trufa', 'CENA', 'PRINCIPAL', 15.00, 'SIN_GLUTEN', 25, false),
(5, 'Tiramisú Clásico', 'Postre italiano con capas de bizcocho empapado en café y crema de mascarpone', 'CENA', 'POSTRE', 7.50, 'ESTANDAR', 40, false),
(6, 'Alitas de Pollo Picantes', 'Alitas fritas bañadas en salsa barbacoa picante con bastones de apio', 'CENA', 'ENTRANTE', 10.00, 'PICANTE', 60, false),
(7, 'Gazpacho Andaluz', 'Sopa fría de tomate, pimiento y pepino, ideal para el verano', 'ALMUERZO', 'ENTRANTE', 6.50, 'VEGANO', 45, false),
(8, 'Hamburguesa de la Casa', 'Carne 100% vacuno, queso cheddar, bacon y huevo frito en pan brioche', 'CENA', 'PRINCIPAL', 13.90, 'ESTANDAR', 100, false),
(9, 'Tostada de Aguacate', 'Pan de masa madre con aguacate triturado, semillas y huevo poché', 'DESAYUNO', 'PRINCIPAL', 9.00, 'ESTANDAR', 50, false),
(10, 'Curry de Verduras', 'Mezcla de verduras de temporada en salsa de curry rojo con leche de coco', 'ALMUERZO', 'PRINCIPAL', 14.50, 'PICANTE', 35, false),
(11, 'Brownie con Helado', 'Bizcocho denso de chocolate con nueces servido con helado de vainilla', 'MERIENDA', 'POSTRE', 6.00, 'ESTANDAR', 30, false),
(12, 'Espaguetis Carbonara', 'Pasta fresca con salsa tradicional de yema de huevo, pecorino y guanciale', 'ALMUERZO', 'PRINCIPAL', 12.00, 'ESTANDAR', 40, false),
(13, 'Tabla de Quesos', 'Selección de quesos nacionales e internacionales con uvas y nueces', 'CENA', 'ENTRANTE', 16.00, 'SIN_GLUTEN', 15, false),
(14, 'Tacos al Pastor', 'Tortillas de maíz con cerdo marinado, piña y cilantro', 'CENA', 'PRINCIPAL', 11.00, 'PICANTE', 80, false),
(15, 'Cheesecake de Frutos Rojos', 'Tarta de queso horneada con mermelada de fresas y arándanos', 'MERIENDA', 'POSTRE', 5.50, 'ESTANDAR', 25, false),
(16, 'Poke Bowl de Atún', 'Arroz de sushi, atún fresco marinado, edamame y algas wakame', 'ALMUERZO', 'PRINCIPAL', 17.00, 'SIN_GLUTEN', 20, false),
(17, 'Croquetas de Jamón', 'Croquetas cremosas caseras de jamón ibérico (Ración de 8)', 'CENA', 'ENTRANTE', 9.50, 'ESTANDAR', 70, false),
(18, 'Lasaña de Berenjena', 'Lasaña vegetal sin pasta, utilizando láminas de berenjena y queso ricotta', 'ALMUERZO', 'PRINCIPAL', 13.50, 'BAJO_CARBOHIDRATO', 20, false),
(19, 'Sopa de Cebolla', 'Sopa reconfortante con pan tostado y queso gratinado por encima', 'CENA', 'ENTRANTE', 8.00, 'ESTANDAR', 30, false),
(20, 'Costillas BBQ', 'Costillar de cerdo asado a baja temperatura con salsa barbacoa ahumada', 'ALMUERZO', 'PRINCIPAL', 22.00, 'ESTANDAR', 15, false);

INSERT INTO PEDIDOS (id, fecha_pedido, estado, total, usuario, direccion) VALUES
(1, '2026-01-01 10:30:00', 'PROCESADO', 150.50, 101, 'Calle Mayor 15, Madrid'),
(2, '2026-01-02 11:15:00', 'ENVIADO', 89.99, 102, 'Avenida de la Constitución 4, Sevilla'),
(3, '2026-01-03 09:00:00', 'PENDIENTE', 45.00, 103, 'Carrer de Balmes 22, Barcelona'),
(4, '2026-01-04 14:45:00', 'ENTREGADO', 210.25, 104, 'Rúa Nova 8, Santiago de Compostela'),
(5, '2026-01-05 16:20:00', 'CANCELADO', 12.50, 105, 'Calle Larios 3, Málaga'),
(6, '2026-01-06 18:00:00', 'PROCESADO', 320.00, 106, 'Paseo de Zorrilla 50, Valladolid'),
(7, '2026-01-07 12:10:00', 'PENDIENTE', 75.60, 107, 'Calle Alfonso I 12, Zaragoza'),
(8, '2026-01-08 08:30:00', 'ENVIADO', 115.00, 108, 'Calle San Fernando 2, Santander'),
(9, '2026-01-09 20:15:00', 'PROCESADO', 55.40, 109, 'Avenida de la Libertad 1, San Sebastián'),
(10, '2026-01-10 13:40:00', 'ENTREGADO', 99.99, 110, 'Calle Recogidas 7, Granada');